spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scheme_agenda_db?currentSchema=agenda_api
    username: agenda_app_user
    password: schemecrud
server:
  port: 8081
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
