version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./create_db_objects.sql:/docker-entrypoint-initdb.d/create_db_objects.sql
    environment:
      POSTGRES_USER: scheme_admin
      POSTGRES_PASSWORD: schemeadmin
      POSTGRES_DB: scheme_agenda_db